namespace HCS.Framework.Enums
{
    public enum ParametrType
    {
        IsOperator,
        OrgGUID,
        OrgPPAGUID,
        UOGUID,
        OGRN,
        INN,
        SNILS,
        FIASHouseGUID,
        LivingRoomGUID,
        PremisesGUID,
        AccountGUID,
        RegistryNumber,
        ContractGuid,
        ContractRootGuid,
        ConractVersionGuid,
        CharterGuid,
        CharterVersionGuid,
        LastVersionOnly,
        SigningDate,
        DateTo,
        DateFrom,
        Year,
        Month
    }
}
